#!/bin/sh

ENV=$1
DELETEDATA=$2

echo "Targeting Elastic Search data for $ENV"

if [ -n "$DELETEDATA" ]; then
  echo "Deleting data...."
  echo "NB: At this time you must have local port 8000"
  echo "to the targeted elastic search node."
  # TODO: Use the correct endpoint here.
  curl -i -XDELETE http\://localhost\:8000/booking-$ENV
  echo
  echo "Done."
fi

# Default to 'cdev' db.
export DB_HOST=nodes.nonprod.kube.tstllc.net
export DB_PORT=32114

# TODO: Get these from secrets.
export DB_USER=root
export DB_PASS=kube-aws

YEARS=$(seq 2010 2020)

for YEAR in $YEARS; do
  echo "Importing data from $YEAR"
  java -jar app-standalone.jar $ENV $YEAR
done
